services:
  - type: web
    name: digit-ai-flask
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths: 
        - Dockerfile
        - app.py
        - mnist_model.keras
        - requirements.txt
        - templates/**
    autoDeploy: true
